name: Deploy to gh-pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to gh-pages branch
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -B gh-pages
          git push -u origin gh-pages --force
